name: GCP Cloud Run
on:
  push:
    branches:
      - master
env:
  PROJECT_ID: sonic-cat-363104
  IMAGE_NAME: email-parser
  # RUN_REGION: us-east1
jobs:
  build:
    name: Build Docker and deploy cloud run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # Setup gcloud CLI
      # - uses: GoogleCloudPlatform/github-actions/setup-gcloud@main
      - uses: google-github-actions/setup-gcloud@v0

        with:
            version: '275.0.0'
            service_account_email: ${{ secrets.SA_EMAIL }}
            service_account_key: ${{ secrets.GCP_SA_KEY_JSON}}

      # Configure gcloud CLI
      - name: gcloud Set up
        run: |
            gcloud config set project $PROJECT_ID

      # Build and push image to Google Container Registry
      - name: Build
        run: gcloud builds submit --tag gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA

      - name: Deploy
        run: gcloud run deploy $PROJECT_ID --image gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA --platform managed

